### ISSUE TITLE
atualizar o readme. 

### ISSUE THREAD

**Issue by JCDMeira** [MatheusOsterno/Frontend-Mentor-Desafio#1]
Como recomendações é possível adicionar imagens, mais detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades, adicionar badges e ser criativo para adicionar mais do seu estilo.

**Comment by MatheusOsterno** [comment]
Obrigado pelo feedback.  =)
Gif animado para Readme, atualizado.
![projeto Sneakers (1)](https://user-images.githubusercontent.com/109709293/199616636-ad8955fc-5721-4030-a17a-abff33075cc2.gif)
